- git:
    repo: "git@github.com:franhp/homepage.git"
    dest: "{{ installation_path}}/homepage"
    update: yes
  register: git_output

- block:
    - name: add env variables file
      copy:
        dest: "{{ installation_path }}/homepage/.env"
        content: |
          IMDB_USERNAME={{ email }}
          IMDB_PASSWORD={{ imdb_passwd }}

    - name: link the database file
      file:
        src: "{{ dropbox_dir }}/Homepage/database.spatialite"
        dest: "{{ installation_path }}/homepage/backend/"
        state: hard

    - name: generate homepage sources
      command: ./refresh.sh
      args:
        chdir: "{{ installation_path }}/homepage/"

    - name: clean old homepage sources
      file:
        path: "{{ installation_path }}/nginx/webpages/homepage"
        state: absent

    - name: copy homepage sources to the static directory
      copy:
        src: "{{ installation_path }}/homepage/frontend/build/"
        dest: "{{ installation_path }}/nginx/webpages/homepage"
        remote_src: yes

  when: git_output.after != git_output.before

- name: copy nginx configuration
  copy:
    src: nginx/homepage.conf
    dest: "{{ installation_path }}/nginx/config/homepage.conf"
# - name: force nginx config reload
#   command: docker exec -it containers_static_1 nginx -s reload
